import Head from "next/head";
import { Inter } from "@next/font/google";
import Image from "next/image";
import Header from "@/components/Text/Header";

const inter = Inter({ subsets: ["latin"] });

function Index() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header mainPage>Check out our new courses <Image src="/icons/hand.svg" alt="Hand pointing down" width={50} height={40} /></Header>
    </>
  );
}

export default Index;